version: '3.9'

services:
  app:
    build: .
    container_name: sonic_app
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "3000:3000"
    command: sh -c "while sleep 1000; do :; done"
    depends_on:
      - db
    environment:
      DATABASE_URL: mysql://user:password@db:3306/sonic

  db:
    image: mysql:8.0
    container_name: sonic_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sonic
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
